"""兼容旧导入路径; 实现位于 domain.library.models."""

from shader_deep.domain.library.models import (
    Candidate as Candidate,
    CandidateRef as CandidateRef,
    Choice as Choice,
    Element as Element,
    ElementScope as ElementScope,
    ExplorationReport as ExplorationReport,
    Feature as Feature,
    FeatureChoice as FeatureChoice,
    FinalFeatureChoice as FinalFeatureChoice,
    FinalRelationChoice as FinalRelationChoice,
    FinalSketch as FinalSketch,
    InstanceGroup as InstanceGroup,
    Library as Library,
    LibraryElement as LibraryElement,
    OutlineElement as OutlineElement,
    OutlineRelation as OutlineRelation,
    Participant as Participant,
    PossibilityLibrary as PossibilityLibrary,
    Relation as Relation,
    RelationChoice as RelationChoice,
    Requirement as Requirement,
    Scopes as Scopes,
    Sketch as Sketch,
    Texts as Texts,
    VisualOutline as VisualOutline,
    compact_data as compact_data,
)
from shader_deep.domain.library.validation import (
    _elements as _elements,
    _fail as _fail,
    _LibraryValidator as _LibraryValidator,
    _overlap as _overlap,
    _scope as _scope,
    _unique as _unique,
    validate_exploration as validate_exploration,
    validate_library as validate_library,
    validate_outline as validate_outline,
)
