"""兼容旧导入路径; 实现位于 domain.validation."""

from shader_deep.domain.validation import (
    REFERENCE_KINDS as REFERENCE_KINDS,
    _evidence_issues as _evidence_issues,
    _hypothesis_link_issues as _hypothesis_link_issues,
    _issue as _issue,
    _mapping_source as _mapping_source,
    _parent_issues as _parent_issues,
    _reference_issues as _reference_issues,
    _region_issues as _region_issues,
    _scope_issues as _scope_issues,
    _sketch_issues as _sketch_issues,
    _source_issue as _source_issue,
    _summary_mapping_issues as _summary_mapping_issues,
    _summary_report_issues as _summary_report_issues,
    _summary_source_issues as _summary_source_issues,
    _summary_visual_source_issues as _summary_visual_source_issues,
    _validate_new_analysis as _validate_new_analysis,
    _validate_summary as _validate_summary,
    _visual_evidence_issues as _visual_evidence_issues,
    _visual_identity_issues as _visual_identity_issues,
    _visual_ids as _visual_ids,
    _visual_source_issue as _visual_source_issue,
    validate_analysis_result as validate_analysis_result,
    validate_analysis_task as validate_analysis_task,
    validate_evidence as validate_evidence,
    validate_lens_visual as validate_lens_visual,
    validate_summary_visual as validate_summary_visual,
    validate_task_visual as validate_task_visual,
    validate_visual_decomposition as validate_visual_decomposition,
    validate_visual_evidence as validate_visual_evidence,
)
